/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment7;

/**
 *
 * @author maria
 */
public class TimeConverter extends javax.swing.JFrame {

    /**
     * Creates new form TimeConverter
     */
    public TimeConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        convertModeBG = new javax.swing.ButtonGroup();
        mainP = new javax.swing.JPanel();
        titleL = new javax.swing.JLabel();
        iconL = new javax.swing.JLabel();
        submitB = new javax.swing.JButton();
        hoursB = new javax.swing.JRadioButton();
        minutesB = new javax.swing.JRadioButton();
        secondsB = new javax.swing.JRadioButton();
        inputSL = new javax.swing.JSlider();
        timeP = new javax.swing.JPanel();
        inputTF = new javax.swing.JTextField();
        inputL = new javax.swing.JLabel();
        equalL = new javax.swing.JLabel();
        outputTF = new javax.swing.JTextField();
        outputL = new javax.swing.JLabel();
        equal2L = new javax.swing.JLabel();
        output2TF = new javax.swing.JTextField();
        output2L = new javax.swing.JLabel();
        messageL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleL.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titleL.setForeground(new java.awt.Color(51, 153, 255));
        titleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleL.setText("Time Converter");

        iconL.setForeground(new java.awt.Color(60, 63, 65));
        iconL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment7/time.png"))); // NOI18N

        submitB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submitB.setText("Submit");
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        convertModeBG.add(hoursB);
        hoursB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hoursB.setSelected(true);
        hoursB.setText("Hours");
        hoursB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursBActionPerformed(evt);
            }
        });

        convertModeBG.add(minutesB);
        minutesB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        minutesB.setText("Minutes");
        minutesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesBActionPerformed(evt);
            }
        });

        convertModeBG.add(secondsB);
        secondsB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        secondsB.setText("Seconds");
        secondsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondsBActionPerformed(evt);
            }
        });

        inputSL.setMajorTickSpacing(50);
        inputSL.setMaximum(1000);
        inputSL.setPaintLabels(true);
        inputSL.setPaintTicks(true);
        inputSL.setSnapToTicks(true);
        inputSL.setValue(0);
        inputSL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                changeSliderValue(evt);
            }
        });

        inputTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTFActionPerformed(evt);
            }
        });

        inputL.setText("Hours");
        inputL.setMaximumSize(new java.awt.Dimension(50, 16));
        inputL.setMinimumSize(new java.awt.Dimension(50, 16));

        equalL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equalL.setText("=");

        outputTF.setEditable(false);
        outputTF.setFocusable(false);
        outputTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputTFActionPerformed(evt);
            }
        });

        outputL.setText("Minutes");
        outputL.setMaximumSize(new java.awt.Dimension(50, 16));
        outputL.setMinimumSize(new java.awt.Dimension(50, 16));

        equal2L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equal2L.setText("=");

        output2TF.setEditable(false);
        output2TF.setFocusable(false);

        output2L.setText("Seconds");

        javax.swing.GroupLayout timePLayout = new javax.swing.GroupLayout(timeP);
        timeP.setLayout(timePLayout);
        timePLayout.setHorizontalGroup(
            timePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equalL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equal2L, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(output2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output2L)
                .addContainerGap())
        );
        timePLayout.setVerticalGroup(
            timePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(timePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equal2L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(output2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(output2L)
                    .addComponent(outputTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalL)
                    .addComponent(inputL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout mainPLayout = new javax.swing.GroupLayout(mainP);
        mainP.setLayout(mainPLayout);
        mainPLayout.setHorizontalGroup(
            mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPLayout.createSequentialGroup()
                        .addComponent(secondsB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(mainPLayout.createSequentialGroup()
                        .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPLayout.createSequentialGroup()
                                .addComponent(iconL, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hoursB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutesB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSL, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPLayout.setVerticalGroup(
            mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPLayout.createSequentialGroup()
                .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(iconL)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(timeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputSL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPLayout.createSequentialGroup()
                        .addComponent(hoursB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondsB))
                    .addComponent(submitB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        messageL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        messageL.setForeground(new java.awt.Color(255, 0, 0));
        messageL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(mainP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(mainP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageL, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        double input = 0;
        double output;
        double output2;

        messageL.setText("");
        try {
            input = Double.parseDouble(inputTF.getText());
        } catch (NumberFormatException e) {
            outputTF.setText("");
            output2TF.setText("");
            messageL.setText("Your input is invalid");
        }

        if (hoursB.isSelected()) {
            output = input * 60;
            output2 = input * 3600;
            outputTF.setText(String.format("%.2f", output));
            output2TF.setText(String.format("%.2f", output2));
        }
        
        if (minutesB.isSelected()) {
            output = input / 60;
            output2 = input * 60;
            outputTF.setText(String.format("%.2f", output));
            output2TF.setText(String.format("%.2f", output2));
        }

        if (secondsB.isSelected()) {
            output = input / 3600;
            output2 = input / 60;
            outputTF.setText(String.format("%.2f", output));
            output2TF.setText(String.format("%.2f", output2));
        }
    }//GEN-LAST:event_submitBActionPerformed

    private void outputTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputTFActionPerformed

    }//GEN-LAST:event_outputTFActionPerformed

    private void hoursBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursBActionPerformed
        inputL.setText("Hours");
        outputL.setText("Minutes");
        output2L.setText("Seconds");
        inputTF.setText("");
        outputTF.setText("");
        output2TF.setText("");
    }//GEN-LAST:event_hoursBActionPerformed

    private void minutesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesBActionPerformed
        inputL.setText("Minutes");
        outputL.setText("Hours");
        output2L.setText("Seconds");
        inputTF.setText("");
        outputTF.setText("");
        output2TF.setText("");
    }//GEN-LAST:event_minutesBActionPerformed

    private void secondsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondsBActionPerformed
        inputL.setText("Seconds");
        outputL.setText("Hours");
        output2L.setText("Minutes");
        inputTF.setText("");
        outputTF.setText("");
        output2TF.setText("");
    }//GEN-LAST:event_secondsBActionPerformed

    private void changeSliderValue(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_changeSliderValue
        inputTF.setText("" + inputSL.getValue());
    }//GEN-LAST:event_changeSliderValue

    private void inputTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTFActionPerformed

    }//GEN-LAST:event_inputTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup convertModeBG;
    private javax.swing.JLabel equal2L;
    private javax.swing.JLabel equalL;
    private javax.swing.JRadioButton hoursB;
    private javax.swing.JLabel iconL;
    private javax.swing.JLabel inputL;
    private javax.swing.JSlider inputSL;
    private javax.swing.JTextField inputTF;
    private javax.swing.JPanel mainP;
    private javax.swing.JLabel messageL;
    private javax.swing.JRadioButton minutesB;
    private javax.swing.JLabel output2L;
    private javax.swing.JTextField output2TF;
    private javax.swing.JLabel outputL;
    private javax.swing.JTextField outputTF;
    private javax.swing.JRadioButton secondsB;
    private javax.swing.JButton submitB;
    private javax.swing.JPanel timeP;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
